### ISSUE TITLE
Feature request: Spout texture sharing support 

### ISSUE THREAD

**Issue by newemka** [milkdrop2077/MilkDrop3#3] opened 2023-04-12 09:30 UTC
For versatility It would be awesome to have spout texture sharing support, then Milkdrop3 render could be used in OBS via Spout as background for streaming or in VJ softwares 
All the information for devs: 
[https://github.com/leadedge/Spout2](https://github.com/leadedge/Spout2)

**Comment by milkdrop2077** [comment] 2023-04-12 22:56
Hey it's on my to-do list! I'm working on adding some other functionalities  at the moment, but one day I will!

**Comment by OfficialIncubo** [comment] 2023-04-14 18:59
I also asked for the Spout integration + I am still doing it, but because of too many errors, I can't do it. If you are done, please DM me on Twitter or Discord the code that you integrated with Spout.

**Comment by OfficialIncubo** [comment] 2023-04-14 19:09
5 months ago, I released the issue about Spout integration on my BeatDrop improvement. Btw, it's still in my to do list.

https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/issues/3

**Comment by Lagaz** [comment] 2023-04-19 19:57
There is a work around for the spout/syphon usage in OBS. Just take the time to pre-record the programs and then stream those video's when desired.

**Comment by milkdrop2077** [comment] 2023-04-19 22:54
Yes you can see the MilkDrop3 window in OBS, add 'Window Capture' in the Sources, then select the MilkDrop 3.exe, and make it fit to your screen's capture size.

**Comment by vdmokstati** [comment] 2023-04-26 03:08
hey .. id suggest to check out implimentation done by nest drop.. they had optimised it a lot more then what beatdrop could do. 
im pretty sure ive mentioned this at vj union software going back years...  very familiar with the subject. but i feel we had moved on from this issue...

**Comment by Lagaz** [comment] 2023-04-26 03:17
Just updated Nestdrop Midnight late last week. At the moment, I've close to 200K presets to curate. While there may be faster programs for viewing presets, Beatdrop is what's on hand. Can't be certain, but I chimed in with the work around of the spout inclusion. Have to say, Nestdrop Spout 2 feature pulls my fat outta fire more times than not. The video's mentioned above are 35 - 50 minutes long.

**Comment by milkdrop2077** [comment] 2023-04-26 04:16
200k presets? you must have ~150k duplicate. There are less than 70k unique presets total, and thousands of them are almost identical. You can clean your collection with a program like Czkawka to remove identical files, then try to remove almost identical files.

NestDrop is cool, next year I'm planing to code something similar, just much better and faster ;)

**Comment by Lagaz** [comment] 2023-04-26 04:29
Much my reasoning on Beatdrop to curate is that earlier this year I stumble upon https://github.com/milkdrop2077/milkdrop2077 . I've been loading 10 or so presets into source folders and running 500 or so mashups based on them. Thanks Milkdrop2077 !  Couple weeks ago fell into a 60 preset collection that uses images for textures. While it may not a big deal to many, with just shy of 2 years under my Milkdrop experience, it's a game changer. Yes, Nestdrop Midnight has the sprite system. The hard transitions using sprites has me digging for more elegant solutions.

**Comment by leadedge** [comment] 2023-05-15 06:52
Hello all..

I was referred to this issue and was prompted to test Spout for DirectX 9 which I haven't done for quite some time. As a result I have been successful in updating my old fork of [BeatDrop](https://github.com/leadedge/BeatDrop). All went well with the latest code and it's also updated for Visual Studio 2022.

The changes could be used in MilkDrop3, but there's a bit more involved because Spout texture sharing requires DirectX9EX instead of just DirectX9 that the original Milkdrop was based on. All the code is commented throughout though if you want to have a look.

**Comment by milkdrop2077** [comment] 2023-05-15 23:21
Hey leadedge! thank you so much for all the information!

**Comment by leadedge** [comment] 2023-05-15 23:30
No problems.

@OfficialIncubo - You can change to Visual Studio 2019. Open BeatDrop.sln and :

Project > Properties > General > Platform Toolset > Visual Studio 1019 (v142)

With re-build, you will get re-definition warnings due to using Windows Kits\10 together with Microsoft DirectX SDK (June 2010). These will not occur with build only. If you want to remove them :

Project > Properties > Include Directories
Include (WindowsSDK_IncludePath) before (DXSDK_DIR)Include

DirectX9EX is an enhanced version of DirectX 9 and required for shared textures. Look at DXcontext.cpp and also search for "DX9EX" in MilkDrop2PcmVisualizer.cpp. There is a function "bool CheckForDirectX9c()" that looks for the correct version on your system.

These links might be useful

https://www.microsoft.com/en-us/download/details.aspx?id=8109

http://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe

**Comment by OfficialIncubo** [comment] 2023-05-16 10:02
Some cons that I found on the latest BeatDrop for Spout release are:

- Preset editing and Preset list navigation didn't work at all.
- Some presets may contain errors because of ns-eel modification.

**Comment by milkdrop2077** [comment] 2023-05-16 23:13
Hey @leadedge quick question : how to recompile your first version of beatdrop with the SpoutLibrary.dll ?

I have this error : 
plugin.obj : error LNK2019: unresolved external symbol _GetSpout@0 referenced in function "public: virtual void __thiscall CPlugin::MyPreInitialize(void)" (?MyPreInitialize@CPlugin@@UAEXXZ)
.\Debug\BeatDrop.exe : fatal error LNK1120: 1 unresolved externals

I am missing some OpenGL library or something? I'm using VS2019 + glut lib

**Comment by leadedge** [comment] 2023-05-17 00:14
The linker isn't finding SpoutLibrary.

I have made a "SpoutLibrary" branch with the original code for reference.

You need a "spoutLibrary" folder as in the repo.

Project > Propertines > Linker > General
add
..\spoutlibrary

Project > Properties > Linker > Input
SpoutLibrary.lib

These might also be needed
opengl32.lib
glu32.lib

Copy SpoutLibrary.dll to your release folder.

**Comment by OfficialIncubo** [comment] 2023-05-17 07:18
These Seven Succurro Presets are sooo epic, but I have a problem about "Succurro - TV Static 1" preset:

- error in shape 0 init code
- error in shape 3 init code
- error in shape 3 per-frame code
- Could not load texture: z.j

One thing is: I need the "zombies_03.jpg" image texture file in order to work.

**Comment by leadedge** [comment] 2023-05-17 07:59
Really sorry but I can't help with the presets.  I understand that some are brilliant.

Some time back there was collaborative work with the developer of [NestDrop](https://nestimmersion.ca/nestdrop.php) and the preset might have been added then. Maybe you will find the missing file in the NestDrop presets.

**Comment by OfficialIncubo** [comment] 2023-09-24 20:03
Hey, @leadedge, I managed to compile the SpoutDX9 version of BeatDrop and I have some cons for you:

- Navigation keys not working, function keys working
- Some presets may be broken
- Ctrl+Z not working.
- The window starts at 720x720, but it's stretched. When I resize it, the visualization stays normal.

The old version (1.0.0.2) works than intended and I don't prefer the SpoutDX9 version of it until it's fixed, but where do I menage to compile the 1.0.0.2 version of BeatDrop?

**Comment by leadedge** [comment] 2023-09-25 05:20
Hi @OfficialIncubo 
I found the bug preventing some keys like Ctrl-Z from working.
I can't help with the presets. Many of these were added during collaborative work and left in the repository. Some might be useful for you.
Starting window size is 1280x720. There was an intention for the output resolution to be independent of the window size but I don't think that was ever implemented.
I updated the Master branch with the key correction and also updated the SpoutLibrary branch to Visual Studio 2022 and new library files. It works OK as far as I can tell. That's the branch you need if you want to compile the original version.

**Comment by OfficialIncubo** [comment] 2023-09-25 07:28
Now the preset functionality and navigation keys now worked!
But... if I reenable the Spout output, it doesn't appear on the reciever.
Plus I implemented a new beat detection algorithm btw.

https://github.com/leadedge/BeatDrop/assets/74858188/d5d51382-92cd-450f-9514-7abf60f10e7a

I changed the SpoutWidth and SpoutHeight to 720. When I open BeatDrop, it doesn't send to Spout. It doesn't support below 1920x1080 resolution.

**Comment by leadedge** [comment] 2023-09-25 07:51
Ok at least the keys work. I will have a look at disable/enable.

I will also look at a 720x720 window. I assume you prefer a square format.
1920x1080 is the initial sending size, independent of the window size and these initial dimensions can be changed before compiling the project. As I mentioned before, this was not completed and re-sizing the window changes the sender resolution to the window size. If the window is not re-sized, the initial resolution remains.

Also I should mention that the main reason for the change to the DirectX9 version is the increased speed and reduction of CPU load. It uses a GPU texture surface instead of pixels from the backbuffer.

**Comment by OfficialIncubo** [comment] 2023-09-25 08:23
> ...these initial dimensions can be changed before compiling the project.

I tried to change the initial dimensions to 720×720, but I started BeatDrop and it doesn't initialize the Spout output to the Sender.

**Comment by OfficialIncubo** [comment] 2023-09-25 11:02
Oh! And if I resize the window if I want, the Spout Reciever info only sends the old resolution info. I want it to respond to the actual resolution.

**Comment by OfficialIncubo** [comment] 2023-09-25 14:22
If I enable the SpoutOutput once, it starts to send it.

Log:

```
[notice] CPlugin::RenderFrame - size change from 0x0 to 1920x1080
[notice] CPlugin::OpenSender(1920, 1080)
[notice] spoutDX9::SetDX9device (0xF4D8540)
[notice] spoutDX9::OpenDirectX9 - hWnd = 0x0000000
[notice] spoutDX9::CreateSharedDX9Texture 1920x1080 - format 22 - handle 0x00008C2
[notice] spoutSenderNames::CreateSender
[notice]     [BeatDrop] 1920x1080, share handle = 0x00008C2, format = 22
[notice] spoutFrameCount::CreateAccessMutex - texture access mutex [BeatDrop_SpoutAccessMutex] created
[notice]     Handle [0x00007FC]
[notice] SpoutFrameCount::EnableFrameCount - frame count semaphore [BeatDrop_Count_Semaphore] exists
[notice]     Handle for access [0x0000734]
```

Then I turned off and I reenabled it. Nothing happened. It won't let me to show this visualizer to sender again.

Plus after the first resize to the smaller window, it shows:
```
[notice] spoutDX9::CreateSharedDX9Texture 1920x1080 - format 22 - handle 0x00013C2
```
...which the sender info is still in 1920×1080. I want to update the resize info to the actual window resolution. Not the old one.

**Comment by OfficialIncubo** [comment] 2023-09-25 14:27
Hey, @leadedge! If I enable the SpoutOutput once, it starts to send it.

Log:

```
[notice] CPlugin::RenderFrame - size change from 0x0 to 1920x1080
[notice] CPlugin::OpenSender(1920, 1080)
[notice] spoutDX9::SetDX9device (0xF4D8540)
[notice] spoutDX9::OpenDirectX9 - hWnd = 0x0000000
[notice] spoutDX9::CreateSharedDX9Texture 1920x1080 - format 22 - handle 0x00008C2
[notice] spoutSenderNames::CreateSender
[notice]     [BeatDrop] 1920x1080, share handle = 0x00008C2, format = 22
[notice] spoutFrameCount::CreateAccessMutex - texture access mutex [BeatDrop_SpoutAccessMutex] created
[notice]     Handle [0x00007FC]
[notice] SpoutFrameCount::EnableFrameCount - frame count semaphore [BeatDrop_Count_Semaphore] exists
[notice]     Handle for access [0x0000734]
```

Then I turned off and I reenabled it. Nothing happened. It won't let me to show this visualizer to sender again.

Plus after the first resize to the smaller window, it shows:
```
[notice] spoutDX9::CreateSharedDX9Texture 1920x1080 - format 22 - handle 0x00013C2
```
...which the sender info is still in 1920×1080. I want to update the resize info to the actual window resolution. Not the old one.

> I will have a look at disable/enable.

Oh. I see. If you are done, then remind me.
Then, please see the window resolution bug.

**Comment by leadedge** [comment] 2023-09-26 03:23
I have been though the whole project to complete the sender size implementation. The aim was to set a fixed sender resolution that does not change when the user re-sizes the window. The resolution can then be much larger than the monitor can display, such as 4096x4096 for large scale projection.

I made a change to SendDX9surface in the SpoutDX9 class to enable this. The same change allows an option for the sender size to be the same as the window. Code comments in milkdropfs.cpp RenderFrame/SendDX9surface describe how to do this.

I also found an error in nseel2/nseel-compiler.c where an intrinsic re-definition was removed without retaining the default definition. This might fix the preset errors.

I hope this allows you to achieve what you want to do. Unfortunately I don't have any more time to spend on this right now.

**Comment by OfficialIncubo** [comment] 2023-09-26 06:27
Ok. The Spout Output now works after reenabling than intended. 

> The aim was to set a fixed sender resolution that does not change when the user re-sizes the window.

Ok. This is the one unimplemented thing (I know?), but the Spout output needs to be reenabled after resizing the BeatDrop window.

> Unfortunately I don't have any more time to spend on this right now.

Ok. Feel free to take a time. The Spout Integration is now finished today, but it remains a BETA feature.

**Comment by leadedge** [comment] 2023-09-26 07:27
The fixed sender resolution is implemented now. As far as I can see it's working OK. The Spout output remains enabled after re-sizing the window. If it has been disabled with Ctrl-Z it remains disabled.

**Comment by OfficialIncubo** [comment] 2023-09-26 11:52
I know.
But one more: When I resize the window, it doesn't sync with the Spout Sender Resolution Info compared to the old one.
Can you please spot what's the issue of it?
As you mentioned to say this to me:
> Unfortunately I don't have any more time to spend on this right now.
You can take a break. I don't want to disturb you at all ;)

**Comment by leadedge** [comment] 2023-09-27 00:10
There was a problem was with the original version. I found a bug in SpoutDX [here](https://github.com/leadedge/BeatDrop/blob/002054c14230d5fd7f70dd4b706c48a3e17a63b6/spoutDX9/SpoutDX9.cpp#L796) where the sender size was updated with class variables before they were updated. Directx9 StretchRect still worked OK and hid the error. I hope the modifications allow you to complete yoor project. By using DirectX9 functions instead of CPU, you can send 4K images at 30fps easily. I won't be taking a break so much as finishing other urgent work.

**Comment by OfficialIncubo** [comment] 2023-09-27 04:42
I... I already changed it.

**Comment by OfficialIncubo** [comment] 2023-09-27 04:44
I... I already changed it.

![image](https://github.com/milkdrop2077/MilkDrop3/assets/74858188/a1016449-630d-4262-bb72-ec55ba90a717)

I think I can paste it after 'm_dwFormat = dwFormat;'...

**Comment by OfficialIncubo** [comment] 2023-09-27 08:25
Ok ok ok ..... OK, I am just a little bit confused hehe 😅
I changed from `spoutsender.SendDX9surface(back_buffer, false)` to `spoutsender.SendDX9surface(back_buffer, true)`. Now it syncs to the BeatDrop window instead of the fixed size without reenabling it confirmed in the comments from line 1230 in milkdropfs.cpp.
```
- If the update flag is true (default), size changes are handled by SendDX9surface.
   Set the initial sender size to the window size in Milkdrop2PcmVisualizer.cpp
```
I didn't notice if `spoutsender.SendDX9surface(back_buffer, true)` is commented, which is not default.

Here is a demo:

https://github.com/milkdrop2077/MilkDrop3/assets/74858188/b5c08ed1-50a2-4edc-8333-8ac3ddec22bd

Now it works than trying to attempt modifying the code in SpoutDX9.cpp.

**Comment by leadedge** [comment] 2023-09-28 01:04
OK I think you have it right. Update true is default. Fixed size allows higher resolution than the monitor for projection.

**Comment by OfficialIncubo** [comment] 2023-09-28 20:02
Oh. I need to say something. I wish there is a Spout Input Feature on BeatDrop, ex. Using OBS Spout Filter. (Ctrl + X hotkey)

You can change to another input while it actually uses more OBS Spout Filter.

Ex. Use 3 OBS Spout Filters, Ctrl + X to activate Spout Input, Ctrl + X again to another input. Ctrl + X to turn off the Spout Input if it's in the last input.

**Comment by leadedge** [comment] 2023-09-28 23:59
Spout input is available in [NestDrop](https://nestimmersion.ca/nestdrop.php). This project was used in the development and remains as an example but I am sorry that I don't have time to develop it further.

**Comment by OfficialIncubo** [comment] 2023-11-28 11:25
I see that you have the Spout integration done! You can close this issue.

**Comment by aleccologne** [comment] 2024-05-22 11:25
> Hey it's on my to-do list! I'm working on adding some other functionalities at the moment, but one day I will!

Any plans on implementing SPOUT support in Milkdrop3 any time soon? 

-Please keep the automation and randomization alive as is, its not only a manual VJ tool, but also a music viz automaton.
-Control over automatically chosen transitions would be a charm, either through transition shapes deletion in folder?

**Comment by OfficialIncubo** [comment] 2024-05-22 21:48
> Spout input is available in [NestDrop](https://nestimmersion.ca/nestdrop.php). This project was used in the development and remains as an example but I am sorry that I don't have time to develop it further.

For Spout Input as Sprites, you can check the issue here: https://github.com/OfficialIncubo/BeatDrop-Music-Visualizer/issues/26

**Closed** 2024-07-11 12:16 UTC
